import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * MiniEngine — E-1 Index Engine 极简复现 (harness)
 *
 * 验证三个核心控制流 (对照 ES 8.12.2 源码):
 *   A. 计划-执行两阶段: 版本冲突在计划阶段判定, 执行阶段按计划落盘
 *      (InternalEngine.java:1305-1383 planIndexingAsPrimary 五分支)
 *   B. append-only 优化: autoGeneratedIdTimestamp 时间戳水位防重试重复
 *      (InternalEngine.java:1059-1090, 注释 L1143-1173)
 *   C. NRT 三级可见性: realtime get (版本表) / refresh (可搜) / commit (持久化)
 *      (InternalEngine.java:865-924 realtimeGetUnderLock; L2022 refresh)
 *
 * 用内存 map + 版本表模拟 (机制复现非完整库)。
 */
public class MiniEngine {

    /** 版本表条目: version + 删除标记 (对照 VersionValue + tombstones) */
    static class VersionValue {
        final long version;
        final boolean deleted;
        VersionValue(long version, boolean deleted) { this.version = version; this.deleted = deleted; }
    }

    /** 写入操作 (对照 Engine.Index) */
    static class IndexOp {
        final String id;
        final Object value;
        final long autoGenTs;      // autoGeneratedIdTimestamp (UNSET=-1)
        final boolean retry;       // isRetry
        final long incomingVersion;
        final boolean ifSeqNoSet;
        IndexOp(String id, Object value, long autoGenTs, boolean retry, long incomingVersion, boolean ifSeqNoSet) {
            this.id = id; this.value = value; this.autoGenTs = autoGenTs;
            this.retry = retry; this.incomingVersion = incomingVersion; this.ifSeqNoSet = ifSeqNoSet;
        }
    }

    static final long UNSET_AUTO_GEN_TS = -1;

    /** 引擎: 版本表 + 已提交文档 + NRT 控制 (对照 InternalEngine) */
    static class Engine {
        final Map<String, VersionValue> versionMap = new ConcurrentHashMap<>();  // LiveVersionMap
        final Map<String, Object> committed = new ConcurrentHashMap<>();          // Lucene 已提交
        volatile boolean refreshed = false;                                       // refresh 开关
        long maxUnsafeAutoIdTimestamp = -1;                                       // 幂等水位

        /** 计划阶段 (planIndexingAsPrimary 简化): 返回计划 (追加/更新/冲突) */
        String plan(IndexOp op) {
            VersionValue cur = versionMap.get(op.id);
            long currentVersion = cur == null ? 0 : cur.version;
            boolean notFoundOrDeleted = cur == null || cur.deleted;
            // 冲突检查
            if (op.ifSeqNoSet && notFoundOrDeleted) return "CONFLICT";   // ifSeqNo 但文档不存在
            if (!notFoundOrDeleted && op.incomingVersion != 0 && op.incomingVersion != currentVersion) {
                return "CONFLICT";                                        // 版本不匹配
            }
            // append-only 优化判定
            if (op.autoGenTs != UNSET_AUTO_GEN_TS) {
                if (op.autoGenTs > maxUnsafeAutoIdTimestamp && !op.retry) {
                    maxUnsafeAutoIdTimestamp = op.autoGenTs;
                    return "APPEND";                                       // 可优化: 直接加
                }
                return "UPDATE";                                           // 重试/旧时间戳: 降级更新
            }
            return "UPDATE";
        }

        /** 执行阶段 (indexIntoLucene 简化): 按计划落盘 + 更新版本表 */
        IndexResult execute(IndexOp op, String plan) {
            if (plan.equals("CONFLICT")) return new IndexResult(false, 0, "version conflict");
            long newVersion = plan.equals("APPEND") ? 1 : (versionMap.containsKey(op.id)
                ? versionMap.get(op.id).version + 1 : 1);
            committed.put(op.id, op.value);                                // 写入 Lucene
            versionMap.put(op.id, new VersionValue(newVersion, false));    // 更新版本表 (maybePutIndexUnderLock)
            return new IndexResult(true, newVersion, "ok");
        }

        /** realtime get (L865-924): 查版本表, 不依赖 refresh */
        Object realtimeGet(String id) {
            VersionValue vv = versionMap.get(id);
            if (vv == null || vv.deleted) return null;
            return committed.get(id);
        }

        /** 非 realtime get: 需要 refresh 后可见 */
        Object committedGet(String id) {
            if (!refreshed) return null;   // 未 refresh 不可见
            VersionValue vv = versionMap.get(id);
            if (vv == null || vv.deleted) return null;
            return committed.get(id);
        }

        void refresh() { refreshed = true; }
    }

    static class IndexResult {
        final boolean success;
        final long version;
        final String error;
        IndexResult(boolean success, long version, String error) {
            this.success = success; this.version = version; this.error = error;
        }
    }
}
